# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r_check_args: --as-cran
sudo: false
cache: packages
warnings_are_errors: false


matrix:
  include:
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_packages:
        - covr
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      after_success:
        - Rscript -e 'covr::codecov()'
        - R CMD INSTALL .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_PAT
          keep-history: true
          local-dir: docs
          on:
            branch: master
